# Future sections (not yet exposed):
# - News
# - Briefings
# - Datasets
# - Dashboards
# - Methods

project:
  type: website
  preview:
    port: 4200
    
website:
  title: "Information Hub"
  site-url: https://sh-publichealth.github.io/info-hub
  repo-url: https://github.com/sh-publichealth/info-hub
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true

  # --------------------
  # Top navigation bar
  # --------------------
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: our-work/index.qmd
        text: Our Work
#     - href: whats-new/index.qmd
#       text: What's New  
#     - href: our-data/index.qmd
#       text: Our Data               
#     - href: how-we-work/index.qmd
#       text: How We Work               
#     - href: about-us/index.qmd
#       text: About Us               

  # --------------------
  # Sidebar (scoped later)
  # --------------------
  sidebar:
      id: tmr-ops
      title: "TMR Operations Manual"
      style: "docked"
      search: true
      collapse-level: 2
      contents:
        - text: Introduction
          href: our-work/index.qmd
        - section: "Total Meal Replacement"
          contents: 
          - text: The Project
            href: our-work/tmr/index.qmd
          - text: Evidence Brief
            href: our-work/tmr/evidence-brief.qmd
          - text: Information Sheet
            href: our-work/tmr/info-sheet-01.qmd
          - section: "Ops Manual"
            contents: 
            - text: Overview
              href: our-work/tmr/index.qmd
            - text: The Study Protocol 
              href: our-work/tmr/protocol.qmd
            - text: Eligibility 
              href: our-work/tmr/eligibility.qmd
            - section: "Participant Visits"
              contents: 
              - text: Participant Flow
                href: our-work/tmr/visits/participant-flow.qmd
              - text: Recruitment
                href: our-work/tmr/visits/recruitment.qmd
              - text: Screening Visit 
                href: our-work/tmr/visits/screening-visit.qmd
              - text: Baseline Visit 
                href: our-work/tmr/visits/baseline-visit.qmd
              - text: Meal Replacement Visits 
                href: our-work/tmr/visits/meal-replacement-visits.qmd
              - text: Food Reintroduction Visits
                href: our-work/tmr/visits/food-reintroduction-visits.qmd
            - section: "SOPs"
              contents: 
              - text: SOP overview
                href: our-work/tmr/sops/index.qmd
              - text: Screening SOP
                href: our-work/tmr/sops/screening-sop.qmd
              - text: Height & Weight SOP 
                href: our-work/tmr/sops/height-weight-sop.qmd
              - text: Baseline SOP
                href: our-work/tmr/sops/baseline-sop.qmd
              - text: Missed Visit SOP
                href: our-work/tmr/sops/missed-visit-sop.qmd
            - section: "Data"
              contents: 
              - text: Overview
                href: our-work/tmr/data/index.qmd
              - text: Analysis Plan 
                href: our-work/tmr/data/sap.qmd
              - text: Data Dictionary
                href: our-work/tmr/data/data-dictionary.qmd
              - text: Data Management Plan
                href: our-work/tmr/data/data-management-plan.qmd
              - text: Data Sharing
                href: our-work/tmr/data/data-sharing.qmd
              - text: Data Anonymisation
                href: our-work/tmr/data/anonymisation.qmd
              - text: Data Monitoring Committee
                href: our-work/tmr/data/dmc-tor.qmd
            - section: "REDCap Guidance"
              contents: 
              - text: Training Overview
                href: our-work/tmr/redcap/index.qmd
format:
  html:
    description: false
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
# touch: 2026-01-11 17:59:30.434
